# Generated by Django 4.1.2 on 2022-11-02 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Res_name', models.CharField(default=' ', max_length=15)),
                ('category', models.CharField(default=' ', max_length=10)),
                ('distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Menu_name', models.CharField(default=' ', max_length=20)),
                ('price', models.IntegerField()),
                ('Res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KWeat.restaurant')),
            ],
        ),
    ]
